name: np.random(stuff)
description: Blogging about stuff in machine learning and computer vision
meta_description: "Blogging about stuff in machine learning and computer vision"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://nawel.github.io'
google_analytics: ''
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Nawel'
